apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  selector:
    app-service: mongodb
  ports:
  - port: 27017




---
apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app-service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app-service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app-service: mongodb
    spec:
      containers:
      - env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MONGODB_ADVERTISED_HOSTNAME
          value: mongodb
        - name: MONGODB_ENABLE_JOURNAL
          value: "true"
        - name: MONGODB_INITIAL_PRIMARY_HOST
          value: mongodb
        - name: MONGODB_INITIAL_PRIMARY_PORT_NUMBER
          value: "27017"
        - name: MONGODB_PORT_NUMBER
          value: "27017"
        - name: MONGODB_REPLICA_SET_MODE
          value: primary
        - name: MONGODB_REPLICA_SET_NAME
          value: rs0
        image: docker.io/bitnami/mongodb:5.0
        name: mongodb
        volumeMounts:
        - mountPath: /mnt/azure
          name: mongodb-data
      restartPolicy: Always
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: pvc-azuredisk
